// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0LKVr-JqBCR_UvmkBqzsL1FAiKBDmXc',
    appId: '1:371210435710:web:8b4d092d2f35f704c46c2f',
    messagingSenderId: '371210435710',
    projectId: 'whatsweb-c9aca',
    authDomain: 'whatsweb-c9aca.firebaseapp.com',
    storageBucket: 'whatsweb-c9aca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0SOFMiKnMOKKY4GDwfRBh1bwh8QrS2M',
    appId: '1:371210435710:android:d12710bac7506fb0c46c2f',
    messagingSenderId: '371210435710',
    projectId: 'whatsweb-c9aca',
    storageBucket: 'whatsweb-c9aca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPQF5eHdbrfv-maVSWz75_I981G24wDA',
    appId: '1:371210435710:ios:c4a2f35afea190acc46c2f',
    messagingSenderId: '371210435710',
    projectId: 'whatsweb-c9aca',
    storageBucket: 'whatsweb-c9aca.appspot.com',
    iosBundleId: 'com.example.mobxFirebaseExemplo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXPQF5eHdbrfv-maVSWz75_I981G24wDA',
    appId: '1:371210435710:ios:cc08a7729e7f2d20c46c2f',
    messagingSenderId: '371210435710',
    projectId: 'whatsweb-c9aca',
    storageBucket: 'whatsweb-c9aca.appspot.com',
    iosBundleId: 'com.example.mobxFirebaseExemplo1.RunnerTests',
  );
}
